package sortrace;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class Animacion extends javax.swing.JFrame {
    static final int FPS_MIN = 0;
    static final int FPS_MAX = 10;
    static final int FPS_INIT = 5;
    public Animacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        velocidad = new JSlider(JSlider.HORIZONTAL, FPS_MIN, FPS_MAX, FPS_INIT);
        botonAceptar=new JButton();
        botonCancelar=new JButton();
        textoSlider=new JLabel();

        //Turn on labels at major tick marks.
        velocidad.setMajorTickSpacing(5);
        velocidad.setMinorTickSpacing(1);
        velocidad.setPaintTicks(true);
        velocidad.setPaintLabels(true);
        Font font = new Font("DejaVu Sans", Font.ITALIC, 14);
        velocidad.setFont(font);
        velocidad.setPreferredSize(new Dimension(300,50));
        velocidad.setValue(Sortrace.getConfig().getVelocidadAnimacion());


        panel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        textoSlider.setFont(new java.awt.Font("DejaVu Sans", Font.PLAIN, 14)); // NOI18N
        textoSlider.setText(Sortrace.getIdioma().getProperty("animacionTextoSlider"));

        botonAceptar.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonAceptar"));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonCancelar.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonCancelar"));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
        });

        //botonAceptar.setPreferredSize(new Dimension(40, 40));
        //botonCancelar.setPreferredSize(new Dimension(40, 40));
        /*FlowLayout layout=new FlowLayout();
        this.setBounds(0,0,400,150);
        layout.preferredLayoutSize(this);
        panel.setLayout(layout);
        panel.setPreferredSize(this.getSize());
        panel.add(textoSlider);
        panel.add(velocidad);
        panel.add(botonAceptar);
        panel.add(botonCancelar);*/
        panel1.setLayout(new FlowLayout());
        ImageIcon imagen=new ImageIcon(getClass().getResource("/util/icon/AjustesAnimacion.png"));
        JLabel im = new JLabel();
        im.setIcon(imagen);
        panel1.setBorder(new EmptyBorder(5,15,0,15));
        panel1.add(im);
        panel1.add(textoSlider);

        panel2.setLayout(new FlowLayout());
        panel2.add(velocidad);

        panel3.setLayout(new FlowLayout());
        panel3.setBorder(new EmptyBorder(0,0,15,0));
        panel3.add(botonAceptar);
        panel3.add(botonCancelar);

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panel1, BorderLayout.NORTH);
        getContentPane().add(panel2, BorderLayout.CENTER);
        getContentPane().add(panel3, BorderLayout.SOUTH);

        this.setTitle(Sortrace.getIdioma().getProperty("tituloAnimacion"));
        ImageIcon icono=new ImageIcon(getClass().getResource("/util/icon/IconoApp.PNG"));
        this.setIconImage(icono.getImage());
        this.setVisible(true);
        if(Sortrace.getConfig().getModo().equals("si")) {
            this.getContentPane().setBackground(Sortrace.getConfig().getFondoModoOscuro());
            panel.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            panel1.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            panel2.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            panel3.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            botonAceptar.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            botonAceptar.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            botonCancelar.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            botonCancelar.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoSlider.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            velocidad.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            velocidad.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            //vistaVector;
        }else{
            this.getContentPane().setBackground(UIManager.getColor ("JFrame.background"));
            panel.setBackground(UIManager.getColor ("JPanel.background"));
            panel1.setBackground(UIManager.getColor ("JPanel.background"));
            panel2.setBackground(UIManager.getColor ("JPanel.background"));
            panel3.setBackground(UIManager.getColor ("JPanel.background"));
            botonAceptar.setBackground(UIManager.getColor("JButton.background"));
            botonAceptar.setForeground(UIManager.getColor("JButton.foreground"));
            botonCancelar.setBackground(UIManager.getColor("JButton.background"));
            botonCancelar.setForeground(UIManager.getColor("JButton.foreground"));
            textoSlider.setForeground(UIManager.getColor("JLabel.foreground"));
            velocidad.setForeground(UIManager.getColor("JSlider.foreground"));
            velocidad.setBackground(UIManager.getColor("JSlider.background"));
        }
        pack();
    }

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        Sortrace.getConfig().setVelocidadAnimacion(velocidad.getValue());
        Sortrace.getConfig().modificarAnimacion();
        this.dispose();
    }
    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider velocidad;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel textoSlider;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
}

