package sortrace;

import javax.swing.*;
import java.awt.*;

public class Animacion extends javax.swing.JFrame {
    static final int FPS_MIN = 0;
    static final int FPS_MAX = 10;
    static final int FPS_INIT = 5;
    public Animacion() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        velocidad = new JSlider(JSlider.HORIZONTAL, FPS_MIN, FPS_MAX, FPS_INIT);
        botonAceptar=new JButton();
        botonCancelar=new JButton();
        textoSlider=new JLabel();

        //Turn on labels at major tick marks.
        velocidad.setMajorTickSpacing(5);
        velocidad.setMinorTickSpacing(1);
        velocidad.setPaintTicks(true);
        velocidad.setPaintLabels(true);
        Font font = new Font("DejaVu Sans", Font.ITALIC, 14);
        velocidad.setFont(font);
        velocidad.setPreferredSize(new Dimension(350,50));

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        textoSlider.setFont(new java.awt.Font("DejaVu Sans", Font.BOLD, 14)); // NOI18N
        textoSlider.setText(Sortrace.getIdioma().getProperty("animacionTextoSlider"));

        botonAceptar.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonAceptar"));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonCancelar.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonCancelar"));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
        });

        //botonAceptar.setPreferredSize(new Dimension(40, 40));
        //botonCancelar.setPreferredSize(new Dimension(40, 40));
        FlowLayout layout=new FlowLayout();
        this.setBounds(0,0,400,150);
        layout.preferredLayoutSize(this);
        panel.setLayout(layout);
        panel.setPreferredSize(this.getSize());
        panel.add(textoSlider);
        panel.add(velocidad);
        panel.add(botonAceptar);
        panel.add(botonCancelar);

        /*panel.setLayout(new GridBagLayout());
        textoSlider.setHorizontalAlignment(JLabel.CENTER);
        textoSlider.setVerticalAlignment(JLabel.NORTH);
        botonAceptar.setHorizontalAlignment(JButton.CENTER);
        botonCancelar.setHorizontalAlignment(JButton.CENTER);

        GridBagConstraints c = new GridBagConstraints();
        c.weightx = 0.0;
        c.weighty = 1;
        c.gridwidth = 1;
        c.gridheight=1;
        c.gridx = 0;
        c.gridy = 0;
        panel.add(textoSlider, c);
        c.gridheight=1;
        c.gridx = 0;
        c.gridy = 2;
        panel.add(velocidad,c);

        c.gridx = 0;
        c.gridy = 3;
        panel.add(botonAceptar,c);

        c.gridx = 1;
        c.gridy = 3;
        panel.add(botonCancelar,c);*/
        /*panel.setLayout(new FlowLayout());
        panel.add(textoColorAsignacion);
        panel.add(botonColorAsignacion);
        panel.add(textoColorComparacion);
        panel.add(botonColorComparacion);
        panel.add(textoColorFijado);
        panel.add(botonColorFijado);
        panel.add(textoModoOscuro);
        panel.add(botonModoOscuro);
        this.add(panel);*/

        this.add(panel);

        this.setVisible(true);
        pack();
    }

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        Sortrace.getConfig().setVelocidadAnimacion(velocidad.getValue());
        Sortrace.getConfig().modificarAnimacion();
        this.dispose();
    }
    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider velocidad;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel textoSlider;
    private javax.swing.JPanel panel;
}

