/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortrace;

import sortrace.auxiliar.Vector;

import javax.swing.*;

import java.awt.*;

import static java.lang.Thread.sleep;

/**
 *
 * @author usuario
 */
public class IntroducirNumeros_IU extends javax.swing.JFrame {


    /**
     * Creates new form IntroducirNumeros_IU
     */
    public IntroducirNumeros_IU(boolean modificar) {
        initComponents();
        if(modificar){
            //this.setBounds(0, 0, 1500, 350);
            error=false;
            this.panelDatos2 = new sortrace.PanelDatos2(Sortrace.getVector().getSize());
            jLabel2.setVisible(true);
            jLabel1.setVisible(false);
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            //.addComponent(panelDatos1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDatos2, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3)

            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    //.addComponent(panelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3))
            );
            this.panelDatos2.setVisible(true);
            this.jPanel1.setVisible(false);
            this.panelDatos2.setVisible(true);
            this.panelDatos2.mostrarNumeros();
        }
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        //panelDatos1 = new sortrace.PanelDatos();
        this.setTitle(Sortrace.getIdioma().getProperty("introducirDatosTitulo"));
        if(longitud==0) {
            panelDatos2 = new sortrace.PanelDatos2(15);
        }else{
            panelDatos2 = new sortrace.PanelDatos2(this.longitud);
        }
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel1.setText(Sortrace.getIdioma().getProperty("introducirDatosEtiquetaTamano"));

        jList1.setModel(new javax.swing.AbstractListModel<Integer>() {
            Integer[] strings = { 1, 2, 3, 4, 5
                ,6, 7, 8, 9, 10
                ,11, 12, 13, 14, 15
                ,16, 17, 18, 19, 20
                ,21, 22, 23, 24, 25
                ,26, 27, 28, 29, 30};
            public int getSize() { return strings.length; }
            public Integer getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jList1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel3.setLayout(new FlowLayout());
        jPanel3.add(botonAceptar);
        jPanel3.add(jButton2);

        jLabel2=new javax.swing.JLabel();
        jLabel2.setText(Sortrace.getIdioma().getProperty("introducirDatosEtiquetaEntrada"));
        jLabel2.setVisible(false);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addComponent(jPanel1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            //.addComponent(panelDatos1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatos2, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3)

        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                //.addComponent(panelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3))
        );
        botonAceptar.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonAceptar"));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        jButton2.setText(Sortrace.getIdioma().getProperty("introducirDatosBotonCancelar"));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        //this.panelDatos1.setVisible(false);
        this.panelDatos2.setVisible(false);

        this.setVisible(true);

        if(Sortrace.getConfig().getModo().equals("si")) {
            botonAceptar.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            botonAceptar.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            jButton2.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            jButton2.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            jLabel1.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            jLabel2.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            jList1.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            jList1.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            jPanel1.setBackground(Sortrace.getConfig().getFondoModoOscuro());
            jPanel3.setBackground(Sortrace.getConfig().getFondoModoOscuro());
            jScrollPane1.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            jScrollPane1.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            this.getContentPane().setBackground(Sortrace.getConfig().getFondoModoOscuro());
        }else{
            botonAceptar.setBackground(UIManager.getColor("JButton.background"));
            botonAceptar.setForeground(UIManager.getColor("JButton.foreground"));
            jButton2.setBackground(UIManager.getColor("JButton.background"));
            jButton2.setForeground(UIManager.getColor("JButton.foreground"));
            jLabel1.setForeground(UIManager.getColor("JLabel.foreground"));
            jLabel2.setForeground(UIManager.getColor("JLabel.foreground"));
            jList1.setBackground(UIManager.getColor ("JList.background"));
            jList1.setForeground(UIManager.getColor("JList.foreground"));
            jPanel1.setBackground(UIManager.getColor ("JPanel.background"));
            jPanel3.setBackground(UIManager.getColor ("JPanel.background"));
            jScrollPane1.setBackground(UIManager.getColor ("JScrollPane.background"));
            jScrollPane1.setForeground(UIManager.getColor("jScrollPane.foreground"));
            this.getContentPane().setBackground(UIManager.getColor("JFrame.background"));
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        // TODO add your handling code here:
        if(this.jPanel1.isVisible()) {
            //this.setBounds(0, 0, 1500, 350);

            this.jPanel1.setVisible(false);
            //this.panelDatos1.setLongitud(this.jList1.getSelectedValue());
            //this.panelDatos1.updatePanel();
            //this.panelDatos1.setVisible(true);
            this.panelDatos2 = new sortrace.PanelDatos2(this.jList1.getSelectedValue());
            this.panelDatos2.repaint();
            this.setBounds(0, 0, panelDatos2.getPreferredSize().width+100, 350);
            jLabel2.setVisible(true);
            jLabel1.setVisible(false);
            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            //.addComponent(panelDatos1, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelDatos2, GroupLayout.Alignment.CENTER,javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3)

            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    //.addComponent(panelDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    //.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3))
            );
            this.panelDatos2.setVisible(true);
        }else{
            añadirDatos();
            if(Sortrace.getAlgoritmo()!=null){
                Sortrace.getAlgoritmo().terminar();
                Sortrace.getAlgoritmo().setVector(Sortrace.getVector().getVector());
                Sortrace.getAlgoritmo().ejecutar();
                Sortrace.getPantalla().mostrarPanelVisualizacion();
            }
            Sortrace.getPantalla().actualizarBotonesArchivo();
            if(!error) {
                JOptionPane.showMessageDialog(this, Sortrace.getIdioma().getProperty("introducirDatosMensajeExito"), Sortrace.getIdioma().getProperty("introducirDatosTituloExito"), JOptionPane.INFORMATION_MESSAGE, (Icon) null);
                this.dispose();
            }
        }

    }
    private void añadirDatos(){
        Vector vector = Sortrace.getVector();
        int[] vectorAux = new int[this.panelDatos2.getLongitud()];

        for(int i = 0; i < vectorAux.length; ++i) {
            if(!this.panelDatos2.getElementos()[i].getText().equals("")) {
                try {
                    vectorAux[i] = Integer.valueOf(this.panelDatos2.getElementos()[i].getText());
                } catch (NumberFormatException var1) {
                    JOptionPane.showMessageDialog(this, Sortrace.getIdioma().getProperty("introducirDatosErrorMensajeFormato"), Sortrace.getIdioma().getProperty("introducirDatosErrorTituloFormato"), 0, (Icon) null);
                    error = true;
                }
            }else{
                JOptionPane.showMessageDialog(this, Sortrace.getIdioma().getProperty("introducirDatosErrorMensajeFormato"), Sortrace.getIdioma().getProperty("introducirDatosErrorTituloFormato"), 0, (Icon) null);
                error = true;
            }
        }

        vector.setVector(vectorAux);
        vector.setSize(this.panelDatos2.getLongitud());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroducirNumeros_IU(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Integer> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    //private sortrace.PanelDatos panelDatos1;
    private sortrace.PanelDatos2 panelDatos2;
    private boolean error;
    // End of variables declaration//GEN-END:variables
    private int longitud=0;
    private int desplazado=0;
}
