package sortrace;

import sortrace.auxiliar.Vector;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author usuario
 */
public class PanelDatos2 extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public PanelDatos2(int longitud) {
        this.longitud=longitud;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Dimension dim=new Dimension(40,25);
        elementos=new javax.swing.JTextField[longitud];
        posiciones=new javax.swing.JLabel[longitud];
        for(int i=0;i<longitud;i++){
            posiciones[i]=new javax.swing.JLabel();
            posiciones[i].setText(""+(i+1));
            elementos[i]=new javax.swing.JTextField();
            elementos[i].setPreferredSize(dim);
        }
        jLabel2.setText("Posicion");
        jLabel3.setText("Elemento");
        jLabel1.setText("Introduzca los datos de entrada del vector");
        //this.setLayout(new GridLayout(2,17));
        this.setLayout(new GridBagLayout());
        jLabel1.setHorizontalAlignment(JLabel.CENTER);
        jLabel1.setVerticalAlignment(JLabel.NORTH);
        jLabel2.setHorizontalAlignment(JLabel.CENTER);
        jLabel3.setHorizontalAlignment(JLabel.CENTER);

        GridBagConstraints c = new GridBagConstraints();
        c.weightx = 0.0;
        c.gridwidth = longitud+1;
        c.weighty = 1;
        c.gridx = 0;
        c.gridy = 0;
       this.add(jLabel1, c);
        c.weightx = 1;
        c.weighty = 1;
        c.gridwidth = 1;
        c.gridx = 0;
        c.gridy = 1;
        this.add(jLabel2,c);
        for(int i=0;i<longitud;i++) {
            c.gridx = i+1;
            posiciones[i].setHorizontalAlignment(JLabel.CENTER);
            posiciones[i].setVerticalAlignment(JLabel.NORTH);
            this.add(posiciones[i],c);
        }
        c.gridx = 0;
        c.gridy = 2;
        this.add(jLabel3,c);
        for(int i=0;i<longitud;i++) {
            c.gridx = i+1;
            this.add(elementos[i],c);
        }
    }
    public int getLongitud() {
        return longitud;
    }

    public void setLongitud(int longitud) {
        this.longitud = longitud;
    }

    public JTextField[] getElementos() {
        return elementos;
    }
    public void mostrarNumeros(){
        Vector vector=Sortrace.getVector();
        for(int i=0;i<vector.getSize();i++){
            elementos[i].setText(Integer.toString(vector.getVector()[i]));
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField []elementos;
    private javax.swing.JLabel []posiciones;
    int longitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
