/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortrace;

import sortrace.auxiliar.Vector;

import javax.swing.*;

import java.awt.*;

import static java.lang.Thread.sleep;

/**
 *
 * @author usuario
 */
public class Visualizacion extends javax.swing.JFrame {


    /**
     * Creates new form IntroducirNumeros_IU
     */
    public Visualizacion() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        textoColorAsignacion = new javax.swing.JLabel();
        textoColorComparacion = new javax.swing.JLabel();
        textoColorFijado = new javax.swing.JLabel();
        textoModoOscuro = new javax.swing.JLabel();

        panel = new javax.swing.JPanel();

        botonColorAsignacion = new javax.swing.JButton();
        botonColorComparacion = new javax.swing.JButton();
        botonColorFijado = new javax.swing.JButton();
        botonModoOscuro = new javax.swing.JButton();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        textoColorAsignacion.setFont(new java.awt.Font("DejaVu Sans", Font.BOLD, 14)); // NOI18N
        textoColorAsignacion.setText(Sortrace.getIdioma().getProperty("visualizacionTextoColorAsignacion"));
        textoColorComparacion.setFont(new java.awt.Font("DejaVu Sans", Font.BOLD, 14)); // NOI18N
        textoColorComparacion.setText(Sortrace.getIdioma().getProperty("visualizacionTextoColorComparacion"));
        textoColorFijado.setFont(new java.awt.Font("DejaVu Sans", Font.BOLD, 14)); // NOI18N
        textoColorFijado.setText(Sortrace.getIdioma().getProperty("visualizacionTextoColorFijado"));
        textoModoOscuro.setFont(new java.awt.Font("DejaVu Sans", Font.BOLD, 14)); // NOI18N
        textoModoOscuro.setText(Sortrace.getIdioma().getProperty("visualizacionTextoModoOscuro"));

        botonColorAsignacion.setText("");
        botonColorAsignacion.setBackground(Sortrace.getConfig().getColorAsignacion());
        botonColorAsignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorAsignacionMouseClicked(evt);
            }
        });
        botonColorComparacion.setText("");
        botonColorComparacion.setBackground(Sortrace.getConfig().getColorComparacion());
        botonColorComparacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorComparacionMouseClicked(evt);
            }
        });
        botonColorFijado.setText("");
        botonColorFijado.setBackground(Sortrace.getConfig().getColorFijado());
        botonColorFijado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonColorFijadoMouseClicked(evt);
            }
        });
        botonModoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonModoOscuroMouseClicked(evt);
            }
        });

        if(Sortrace.getConfig().getModo().equals("si")) {
            botonModoOscuro.setText("Desactivar");
            panel.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            textoModoOscuro.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorComparacion.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorAsignacion.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorFijado.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            botonModoOscuro.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            botonModoOscuro.setForeground(Sortrace.getConfig().getTextoModoOscuro());
        }else{
            botonModoOscuro.setText("Activar");
            panel.setBackground(UIManager.getColor ("Panel.background"));
            textoModoOscuro.setForeground(UIManager.getColor("JLabel.background"));
            textoColorComparacion.setForeground(UIManager.getColor("JLabel.foreground"));
            textoColorAsignacion.setForeground(UIManager.getColor("JLabel.foreground"));
            textoColorFijado.setForeground(UIManager.getColor("JLabel.foreground"));
            botonModoOscuro.setBackground(UIManager.getColor("JButton.background"));
            botonModoOscuro.setForeground(UIManager.getColor("JButton.foreground"));
        }
        botonColorAsignacion.setPreferredSize(new Dimension(40, 40));
        botonColorComparacion.setPreferredSize(new Dimension(40, 40));
        botonColorFijado.setPreferredSize(new Dimension(40, 40));
        botonModoOscuro.setPreferredSize(new Dimension(40, 40));

        /*panel.setLayout(new FlowLayout());
        panel.add(textoColorAsignacion);
        panel.add(botonColorAsignacion);
        panel.add(textoColorComparacion);
        panel.add(botonColorComparacion);
        panel.add(textoColorFijado);
        panel.add(botonColorFijado);
        panel.add(textoModoOscuro);
        panel.add(botonModoOscuro);
        this.add(panel);*/
        GridLayout gridLayout=new GridLayout();
        gridLayout.setRows(4);
        gridLayout.setHgap(10);
        gridLayout.setColumns(2);
        gridLayout.setVgap(10);
        panel.setLayout(gridLayout);
        panel.add(textoColorAsignacion);
        panel.add(botonColorAsignacion);
        panel.add(textoColorComparacion);
        panel.add(botonColorComparacion);
        panel.add(textoColorFijado);
        panel.add(botonColorFijado);
        panel.add(textoModoOscuro);
        panel.add(botonModoOscuro);
        this.add(panel);

        this.setVisible(true);
        pack();
    }

    private void botonColorAsignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        Color colorAnt = Sortrace.getConfig().getColorAsignacion();
        Color colorNew = JColorChooser.showDialog(this, Sortrace.getIdioma().getProperty("tituloColorChooser"), colorAnt);
        if(colorNew!=null){
            Sortrace.getConfig().setColorAsignacion(colorNew);
            Sortrace.getConfig().modificarAjustesVisualizacion();
            botonColorAsignacion.setBackground(colorNew);
        }
    }
    private void botonColorComparacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        Color colorAnt = Sortrace.getConfig().getColorComparacion();
        Color colorNew = JColorChooser.showDialog(this, Sortrace.getIdioma().getProperty("tituloColorChooser"), colorAnt);
        if(colorNew!=null){
            Sortrace.getConfig().setColorComparacion(colorNew);
            Sortrace.getConfig().modificarAjustesVisualizacion();
            botonColorComparacion.setBackground(colorNew);
        }
    }
    private void botonColorFijadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        Color colorAnt = Sortrace.getConfig().getColorAsignacion();
        Color colorNew = JColorChooser.showDialog(this, Sortrace.getIdioma().getProperty("tituloColorChooser"), colorAnt);
        if(colorNew!=null){
            Sortrace.getConfig().setColorAsignacion(colorNew);
            Sortrace.getConfig().modificarAjustesVisualizacion();
            botonColorAsignacion.setBackground(colorNew);
        }
    }
    private void botonModoOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
        if(Sortrace.getConfig().getModo().equals("si")) {
            Sortrace.getConfig().setModo("no");
            botonModoOscuro.setText("Activar");
            panel.setBackground(UIManager.getColor ( "Panel.background" ));
            textoModoOscuro.setForeground(UIManager.getColor("JLabel.background"));
            textoColorComparacion.setForeground(UIManager.getColor("JLabel.foreground"));
            textoColorAsignacion.setForeground(UIManager.getColor("JLabel.foreground"));
            textoColorFijado.setForeground(UIManager.getColor("JLabel.foreground"));
            botonModoOscuro.setBackground(UIManager.getColor("JButton.background"));
            botonModoOscuro.setForeground(UIManager.getColor("JButton.foreground"));
            Sortrace.getPantalla().actualizarModo();
        }else{
            Sortrace.getConfig().setModo("si");
            botonModoOscuro.setText("Desactivar");
            panel.setBackground(Sortrace.getConfig().getPanelModoOscuro());
            textoModoOscuro.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorComparacion.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorAsignacion.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            textoColorFijado.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            botonModoOscuro.setBackground(Sortrace.getConfig().getBotonModoOscuro());
            botonModoOscuro.setForeground(Sortrace.getConfig().getTextoModoOscuro());
            Sortrace.getPantalla().actualizarModo();
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirNumeros_IU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonColorAsignacion;
    private javax.swing.JButton botonColorComparacion;
    private javax.swing.JButton botonColorFijado;
    private javax.swing.JButton botonModoOscuro;
    private javax.swing.JLabel textoColorAsignacion;
    private javax.swing.JLabel textoColorComparacion;
    private javax.swing.JLabel textoColorFijado;
    private javax.swing.JLabel textoModoOscuro;
    private javax.swing.JPanel panel;
}
